#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.0
#  in conjunction with Tcl version 8.6
#    Dec 08, 2020 02:34:48 AM +03  platform: Windows NT

import sys
import Core
from Core import *
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    createExperiment()
    createLeftPanel(gui.Frame1)
    row = createMiddlePanel(gui.Frame2)
    row = createRightPanel(gui.Frame2, row)
    

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import CRISPResso2UI
    CRISPResso2UI.vp_start_gui()




